version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.12.2-management
    container_name: rabbitmq_management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "1234"
      RABBITMQ_MANAGEMENT: "true"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - konsi_network
    restart: always


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - konsi_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - konsi_network

volumes:
  rabbitmq_data:
  redis_data:
  elasticsearch_data:

networks:
  konsi_network:
    driver: bridge